- name: Check rbenv Plugin ruby-build Installed
  shell: source /etc/profile; rbenv versions | awk '/{{ rubyBuildVersion }}/{print $2}'
  register: result
  changed_when: result.stdout.find('{{ rubyBuildVersion }}') != 0

#- debug: msg='{{ result.stdout.find('2.0.0-p247') }}'
#- debug: msg='{{ result.changed }}'

- name: Install Ruby from rbenv With ruby-build
  shell: source /etc/profile; rbenv install {{ rubyBuildVersion }}
  when: result.stdout.find('{{ rubyBuildVersion }}') != 0

- name: Build ruby change global
  shell: source /etc/profile; rbenv global {{ rubyBuildVersion }}; rbenv rehash
  when: result.stdout.find('{{ rubyBuildVersion }}') != 0