- name: Install vim-enhanced
  yum: pkg=vim-enhanced state=installed
  tags: vim-enhanced

- name: .vim Create Dir
  file: path=/home/{{ ansible_env.SUDO_USER }}/.vim state=directory owner={{ ansible_env.SUDO_USER}} group={{ ansible_env.SUDO_USER }}

