- name: Install Depencecy packages
  yum: pkg={{ item }} state=installed
  with_items:
    - redis
  tags: hubot

- name: start redis
  service: name=redis state=started

- name: Check npm module hubot
  shell: source /etc/profile; npm list -g | awk '/hubot/{print $2}'
  register: result
  changed_when: result.stdout.find('/hubot') == 0

- name: npm install hubot and denpencecy modules
  shell: source /etc/profile; npm install -g {{ item }}
  with_items:
    - hubot
    - coffee-script
  when: result.stdout.find('/hubot') == 0

- name: hubot profile Settings
  template: src=hubot.sh.j2 dest=/etc/profile.d/hubot.sh mode=0644