- name: check elasticsearch installed
  service: name=elasticsearch state=started
  register: installed
  ignore_errors: yes
  tags: es

- name: add user
  user: name=elasticsearch
  tags: es

- name: download elasticsearch
  shell: curl -OL https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ version }}.tar.gz chdir=/usr/local creates=/usr/local/elasticsearch
  tags: es

- name: unzip file
  shell: tar zxvf elasticsearch-{{ version }}.tar.gz chdir=/usr/local creates=/usr/local/elasticsearch
  tags: es

- name: rename directory
  shell: mv elasticsearch-{{ version }} elasticsearch chdir=/usr/local creates=/usr/local/elasticsearch
  tags: es

- name: remove file
  file: path=/usr/local/elasticsearch-{{ version }}.tar.gz state=absent
  tags: es

- name: change permission
  file: path=/usr/local/elasticsearch mode=0755 recurse=yes
  tags: es

- name: download elasticsearch-rpms
  shell: wget -O /etc/init.d/elasticsearch https://raw.github.com/tavisto/elasticsearch-rpms/master/SOURCES/init.d-elasticsearch
  when: installed|failed
  tags: es

- name: make directories
  file: path=/var/{{ item }}/elasticsearch recurse=yes group=elasticsearch state=directory mode=0755
  with_items:
    - run
    - log
    - lib
  tags: es

- name: change permission
  shell: chown -R elasticsearch:elasticsearch /var/{{ item }}/elasticsearch
  with_items:
    - run
    - log
    - lib
  changed_when: installed|failed
  tags: es

- name: add configure file
  template: src=elasticsearch.j2 dest=/etc/init.d/elasticsearch mode=0755
  when: installed|failed
  tags: es

- name: make template directory
  file: path=/usr/local/elasticsearch/config/templates state=directory mode=0755
  tags: es

- name: set template file
  template: src=template_1.j2 dest=/usr/local/elasticsearch/config/templates/template_1.json mode=0755
  tags: es

- name: run elasticsearch
  service: name=elasticsearch state=started enabled=yes
  tags: es
