- name: Check whether composer has already been installed
  stat: path=/usr/local/bin/composer
  register: composer_stat
  tags: php-composer

- name: install composer
  shell: |
    if [ -e /etc/profile.d/phpenv.sh ];then
      source /etc/profile.d/phpenv.sh
    fi
    curl -s https://getcomposer.org/installer | php && mv -v composer.phar /usr/local/bin/composer
  when: composer_stat.stat.exists==false
  tags: php-composer

- name: deploy /etc/profile.d/composer.sh
  copy: src=composer.sh dest=/etc/profile.d/composer.sh owner=root group=root mode=0755 
  when: composer_stat.stat.exists==false
  tags: php-composer

