- name: install dependencis
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
     - cmake

- name: check installed mysql
  shell: |
      if [ $(/usr/local/mysql/bin/mysql --version|grep -c {{ mysql_version }}) -eq 0 ];then
        echo 'not installed'
      else
        echo 'installed'
      fi
  register: installed
  changed_when: installed.stdout!='installed' 
  tags: mysql

- name: install mysql {{ mysql_version }}
  shell: |
      wget http://downloads.mysql.com/archives/get/file/mysql-{{ mysql_version }}.tar.gz
      tar vxf mysql-{{ mysql_version }}.tar.gz
      cd mysql-{{ mysql_version }}
      cmake . -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DWITH_EXTRA_CHARSETS=all -DWITH_PIC=1
      make -j 4
      make install
      chdir='/tmp/'
  when: installed.changed
  tags: mysql

- name: create mysql group
  group: name=mysql state=present
  when: installed.changed

- name: create mysql user
  user: name=mysql group=mysql
  tags: mysql
  when: installed.changed

- name: make directory /var/lib/mysql
  file: path=/var/lib/mysql state=directory owner=mysql group=mysql mode=0775
  when: installed.changed

- name: init system dayabase
  shell: |
      /usr/local/mysql/scripts/mysql_install_db --datadir=/var/lib/mysql --user=mysql --basedir=/usr/local/mysql
      chdir='/usr/local/mysql/'
  when: installed.changed

- name: set permissions
  file: path=/var/lib/mysql owner=mysql group=mysql mode=0775 recurse=yes
  when: installed.changed

- name: copy /usr/local/mysql/support-files/mysql.server to /etc/init.d/mysqld
  shell: cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld creates=/etc/init.d/mysqld
  when: installed.changed

- name: deploy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=mysql group=mysql mode=0755
  when: installed.changed

- name: deploy /etc/profile.d/mysql.sh
  template: src=mysql.sh dest=/etc/profile.d/mysql.sh owner=root group=root mode=0755
  when: installed.changed

- name: start mysql
  service: name=mysqld state=started enabled=yes
  when: installed.changed


