- name: Check for installed apps(virtualbox)
  shell: brew cask list | awk '/^virtualbox$/{print $1}'
  register: cask_list 
  changed_when: cask_list.stdout.find('virtualbox') != 0

- name: install cask virtualbox
  shell: brew cask install virtualbox
  when: cask_list.stdout.find('virtualbox') != 0
