- name: Gemfile Set Current Dir
  template: src=Gemfile.j2 dest={{ currentDir }}/Gemfile mode=0775

- name: Bundle Install
  shell: source /etc/profile; bundle install chdir="{{ currentDir }}"
  register: result
  changed_when: result.stdout.find('Fetching') != -1

#- debug: msg={{ result.stdout }}

